# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Joe Ma
title: Software Development Engineer @ Amazon
email: joema.dev@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: mrjoema
github_username:  mrjoema
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: hokyinma
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Joe and I'm a Software Development Engineer @ Amazon. Before joining Amazon, I was working as SDE in Microsoft and OfferUp.

  I am most skilled in: <mark>TypeScript</mark> <mark>Java</mark> <mark>Python</mark> <mark>AWS</mark> <mark>Web Development</mark> <mark>Mobile Development</mark> <mark>Fullstack Development</mark> <mark>Machine Learning</mark>

content:

  - title: Job Contact
    layout: text
    content: | # this will include new lines to allow paragraphs
        - Native Android and iOS development
        - Web development
        - Fullstack and Backend development

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Dynamic 365 x PowerApps - Run Canvas app from Model Driven App
        link: https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embed-canvas-app-in-form
        description: | # this will include new lines to allow paragraphs
          I implemented the PowerApps SDK and took the ownership from end to end. The SDK allows other 3rd parties such as Dynamic 365 to host the canvas app on D365's model driven app.

      - layout: top-middle
        title: PowerApps Mobile App Governacne - Make PowerApps available for US government 
        link: https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government
        description: | # this will include new lines to allow paragraphs
          I implmented the config router that switches to different config based on the region that customer chose. It ensures the data are aggregated and sent to coresponding endpoint correctly. 
      
      - layout: top-middle
        title: OfferUp Seller Ads (Android) - Allow customer to promote their items for sale
        link: https://help.offerup.com/hc/en-us/articles/360031994412-Promote-your-items
        description: | # this will include new lines to allow paragraphs
          I implmented the SDK that syncs with Google API and OfferUp for one time and subscription payments so users can pay for item promotion.
      
      - layout: top-middle
        title: Predict the NYC traffic safety using Machine Learning
        link: https://dl.acm.org/doi/10.1145/3093241.3093291
        description: | # this will include new lines to allow paragraphs
          I worked as an Undergraduate Research in ML field and implemented the model to predict NYC traffic safety using ML. The research paper was selected by International Conference on Compute and Data Analysis

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # - layout: left
      #   title: Amazon.com
      #   link: boringcompany.com
      #   # link_text: boringcompany.com
      #   sub_title: Software Development Engineer
      #   caption: Aug 2020 - Present
      #   quote: >
      #     Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
      #   description: | # this will include new lines to allow paragraphs
      #       Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

    - layout: left
      title: Amazon.com
      link: amazon.com
      # link_text: boringcompany.com
      sub_title: Software Development Engineer
      caption: Aug 2020 - Present
      description: | # this will include new lines to allow paragraphs
        I work on ML infrastructure to develop the infrastructure that accelerate the productivity of scientist's ML model development in Amazon Prime
    
    - layout: left
      title: Microsoft
      link: microsoft.com
      # link_text: boringcompany.com
      sub_title: Software Development Engineer
      caption: Aug 2018 - Aug 2020
      description: | # this will include new lines to allow paragraphs
        I worked on Web team and mobile team in PowerApps that optimizes user experience in web and mobile app of PowerApps by developing new features and optimizing its performance
    
    - layout: left
      title: OfferUp
      link: offerup.com
      # link_text: boringcompany.com
      sub_title: Software Development Engineer
      caption: Jul 2017 - Jul 2018
      description: | # this will include new lines to allow paragraphs
        I worked on OfferUp Android team to develop features related to monetization such as ads, and item promotions.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Washington
        caption: 2015 - 2017
        sub_title: BSc Computer Science and Software Engineering
        quote:
        description: | # this will include new lines to allow paragraphs
          I worked as an Undergraduate Research in ML field and published a research paper into ACM.
          Analyze NYC Transportation to Mitigate Speeding and Explore New Business Models Using Machine Learning:
          https://dl.acm.org/doi/10.1145/3093241.3093291
      
      - layout: left
        title: Skagit Valley College
        caption: 2014 - 2015
        sub_title: Major in Computer Science
        description: | # this will include new lines to allow paragraphs
          I studyed relative courses to accumulate credits for university transfering.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
